export {
  cmdInit,
  cmdEnable,
  cmdDisable,
  cmdToggle,
  cmdStatus,
  cmdReset,
  cmdSetVoice,
  cmdSetRate,
  cmdSetVolume,
  cmdSetLanguage,
  cmdListVoices,
  cmdSpeak,
  cmdVersion,
  cmdEnableAutoUpdate,
  cmdDisableAutoUpdate,
  cmdHelp,
} from './commands.js';
